version: '3.8'

services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: user_todo
      POSTGRES_PASSWORD: 2905
      POSTGRES_DB: api-todo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    # docker-compose up ---build
    # comando que starta o docker container server